services:
  discecho:
    image: discecho:${DISCECHO_VERSION:-dev}
    container_name: discecho
    runtime: nvidia
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg1:/dev/sg1
      - /dev/sr1:/dev/sr1
      - /dev/sg2:/dev/sg2
    group_add:
      - "24"
    volumes:
      - /mnt/mediastaging/discecho:/library
      - ./.docker-data:/var/lib/discecho
      - /mnt/redumpdats:/var/lib/discecho/redump
      - /mnt/mediastaging/discecho-spool:/var/lib/discecho/spool
      - /run/udev:/run/udev:ro
      - /sys:/sys:ro
      - /dev:/dev
    environment:
      DISCECHO_ADDR: ":8088"
      DISCECHO_LIBRARY: "/library"
      DISCECHO_DATA: "/var/lib/discecho"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
